# Generated by Django 4.0.3 on 2022-06-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrCodeApp', '0003_website_delete_personel_delete_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
            ],
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
