# Generated by Django 4.0.3 on 2022-06-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrCodeApp', '0005_qrcode_get_email_qrcode_name_qrcode_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('get_email', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='get_email',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='phone',
        ),
    ]
