# Generated by Django 4.0.3 on 2022-06-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrCodeApp', '0006_person_remove_qrcode_get_email_remove_qrcode_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='get_email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
